[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[101]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw,gsm
auth=101
aors=101
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
direct_media=no

[101]
type=auth
auth_type=userpass
password=password101
username=101

[101]
type=aor
max_contacts=1

[102]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw,gsm
auth=102
aors=102
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
direct_media=no

[102]
type=auth
auth_type=userpass
password=password102
username=102

[102]
type=aor
max_contacts=1
