// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using backend.Data;

#nullable disable

namespace backend.Migrations.Modular
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "access_key_status", new[] { "active", "revoked", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "action_execution_status", new[] { "pending", "running", "completed", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "action_type", new[] { "system", "workflow", "integration", "webhook" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "api_key_status", new[] { "active", "revoked", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "call_direction", new[] { "inbound", "outbound" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "call_session_status", new[] { "queued", "ringing", "active", "transferred", "completed", "failed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "call_transfer_status", new[] { "requested", "ringing", "accepted", "completed", "rejected", "failed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "handoff_status", new[] { "pending", "delivered", "accepted", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "human_agent_status", new[] { "offline", "available", "break", "not_ready", "in_call" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "license_status", new[] { "active", "inactive", "expired", "cancelled", "suspended" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "metric_type", new[] { "call_duration", "call_minutes", "transfer_count", "recording_minutes", "agent_session_minutes" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "participant_type", new[] { "customer", "ai_agent", "human_agent" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "partner_relationship_status", new[] { "active", "inactive", "suspended" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "plan_tier", new[] { "free", "starter", "growth", "enterprise" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "recording_status", new[] { "pending", "in_progress", "completed", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "subscription_status", new[] { "active", "past_due", "cancelled", "expired", "trialing" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", new[] { "active", "inactive", "suspended" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "workflow_execution_status", new[] { "pending", "running", "completed", "failed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.AgentUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsOnline");

                    b.HasIndex("Status");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("agent_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 30, 16, 11, 25, 211, DateTimeKind.Utc).AddTicks(2249),
                            IsOnline = false,
                            PasswordHash = "admin",
                            Status = "Offline",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("backend.Models.CallRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CallerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("HandledByAgentId")
                        .HasColumnType("integer");

                    b.Property<string>("RecordingUrl")
                        .HasColumnType("text");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HandledByAgentId");

                    b.HasIndex("RoomName");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.ToTable("call_records", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.ActionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("InputSchemaJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OutputSchemaJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("action_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            ActionType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Transfers the call to an available human agent within the same LiveKit room.",
                            DisplayName = "Transfer to Human",
                            IsActive = true,
                            IsSystem = true,
                            Name = "transfer_to_human",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            ActionType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ends the current call session.",
                            DisplayName = "End Call",
                            IsActive = true,
                            IsSystem = true,
                            Name = "end_call",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("backend.Models.Domain.ActionExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CallSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkflowExecutionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActionDefinitionId");

                    b.HasIndex("CallSessionId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowExecutionId");

                    b.ToTable("action_executions", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.CallConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("call_configurations", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.CallConfigurationAction", b =>
                {
                    b.Property<Guid>("CallConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("CallConfigurationId", "ActionDefinitionId");

                    b.HasIndex("ActionDefinitionId");

                    b.ToTable("call_configuration_actions", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.CallHandoff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("CallSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CallTransferId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextDataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("FromParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<Guid>("ToHumanAgentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CallSessionId");

                    b.HasIndex("CallTransferId")
                        .IsUnique();

                    b.HasIndex("FromParticipantId");

                    b.HasIndex("Status");

                    b.HasIndex("ToHumanAgentId");

                    b.ToTable("call_handoffs", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.CallLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("CallSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("HangupCause")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<int>("LegIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ParticipantIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CallSessionId");

                    b.HasIndex("Kind");

                    b.HasIndex("CallSessionId", "LegIndex")
                        .IsUnique();

                    b.ToTable("call_legs", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.CallParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CallSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("HumanAgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("LivekitIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LivekitParticipantSid")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ParticipantType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CallSessionId");

                    b.HasIndex("HumanAgentId");

                    b.HasIndex("ParticipantType");

                    b.ToTable("call_participants", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.CallRecording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CallSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CallSessionId");

                    b.HasIndex("ObjectKey");

                    b.HasIndex("Status");

                    b.ToTable("call_recordings", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.CallSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CallConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DialedNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("LivekitRoomName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LivekitRoomSid")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OriginSipConnectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PersonaVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkflowVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("CallConfigurationId");

                    b.HasIndex("LivekitRoomName");

                    b.HasIndex("OriginSipConnectionId");

                    b.HasIndex("PersonaVersionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowVersionId");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("call_sessions", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.CallTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("CallSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("FromParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetSnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<Guid?>("ToHumanAgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CallSessionId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("FromParticipantId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("Status");

                    b.HasIndex("ToHumanAgentId");

                    b.ToTable("call_transfers", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.HumanAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentCalls")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Status");

                    b.ToTable("human_agents", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.HumanAgentAccessKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("HumanAgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HumanAgentId");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("human_agent_access_keys", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.HumanAgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("HumanAgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("LivekitIdentity")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAt");

                    b.HasIndex("HumanAgentId");

                    b.HasIndex("Status");

                    b.ToTable("human_agent_sessions", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.ToTable("knowledge_bases", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<Guid>("KnowledgeDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeDocumentId");

                    b.HasIndex("KnowledgeDocumentId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("knowledge_chunks", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeBaseId");

                    b.HasIndex("Status");

                    b.ToTable("knowledge_documents", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.ToTable("personas", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.PersonaAction", b =>
                {
                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("PersonaId", "ActionDefinitionId");

                    b.HasIndex("ActionDefinitionId");

                    b.ToTable("persona_actions", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.PersonaKnowledgeBase", b =>
                {
                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("PersonaId", "KnowledgeBaseId");

                    b.HasIndex("KnowledgeBaseId");

                    b.ToTable("persona_knowledge_bases", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.PersonaVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsPublished");

                    b.HasIndex("PersonaId");

                    b.HasIndex("PersonaId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("persona_versions", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EntitlementsJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlatformPlan")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Tier");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.SipConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AllowedIps")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DispatchRuleId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LkTrunkId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MaxConcurrentCalls")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<string[]>("Numbers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("LkTrunkId")
                        .IsUnique();

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("sip_connections", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.SipDestination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallTo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("sip_destinations", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.UsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CallSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CallSessionId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("LicenseId");

                    b.HasIndex("MetricType");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("PartnerId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("usage_records", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.WorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CallSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("StateJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CallSessionId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowVersionId");

                    b.ToTable("workflow_executions", (string)null);
                });

            modelBuilder.Entity("backend.Models.Domain.WorkflowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsPublished");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("WorkflowId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("workflow_versions", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamptz");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("api_keys", "identity");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("LimitsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartnerPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId");

                    b.HasIndex("PartnerPlanId");

                    b.HasIndex("StartsAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("licenses", "identity");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationName");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("partners", "identity");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.PartnerExternalCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ExternalCustomerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlatformUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlatformUserId");

                    b.HasIndex("PartnerId", "ExternalCustomerId")
                        .IsUnique();

                    b.ToTable("partner_external_customers", "identity");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.PartnerPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EntitlementsJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PartnerId");

                    b.ToTable("partner_plans", (string)null);
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.PartnerRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("CustomerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("PartnerId", "CustomerUserId")
                        .IsUnique();

                    b.ToTable("partner_relationships", "identity");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("DefaultPersonaId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsPartner")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PremiumCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("StandardCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DefaultPersonaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("backend.Models.CallRecord", b =>
                {
                    b.HasOne("backend.Models.AgentUser", "HandledByAgent")
                        .WithMany()
                        .HasForeignKey("HandledByAgentId");

                    b.Navigation("HandledByAgent");
                });

            modelBuilder.Entity("backend.Models.Domain.ActionExecution", b =>
                {
                    b.HasOne("backend.Models.Domain.ActionDefinition", "ActionDefinition")
                        .WithMany("ActionExecutions")
                        .HasForeignKey("ActionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Domain.CallSession", "CallSession")
                        .WithMany("ActionExecutions")
                        .HasForeignKey("CallSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Domain.WorkflowExecution", "WorkflowExecution")
                        .WithMany()
                        .HasForeignKey("WorkflowExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActionDefinition");

                    b.Navigation("CallSession");

                    b.Navigation("WorkflowExecution");
                });

            modelBuilder.Entity("backend.Models.Domain.CallConfiguration", b =>
                {
                    b.HasOne("backend.Models.Domain.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithMany("CallConfigurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Domain.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Persona");

                    b.Navigation("User");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("backend.Models.Domain.CallConfigurationAction", b =>
                {
                    b.HasOne("backend.Models.Domain.ActionDefinition", "ActionDefinition")
                        .WithMany("CallConfigurationActions")
                        .HasForeignKey("ActionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Domain.CallConfiguration", "CallConfiguration")
                        .WithMany("CallConfigurationActions")
                        .HasForeignKey("CallConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionDefinition");

                    b.Navigation("CallConfiguration");
                });

            modelBuilder.Entity("backend.Models.Domain.CallHandoff", b =>
                {
                    b.HasOne("backend.Models.Domain.CallSession", "CallSession")
                        .WithMany("Handoffs")
                        .HasForeignKey("CallSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Domain.CallTransfer", "CallTransfer")
                        .WithOne("Handoff")
                        .HasForeignKey("backend.Models.Domain.CallHandoff", "CallTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Domain.CallParticipant", "FromParticipant")
                        .WithMany()
                        .HasForeignKey("FromParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Domain.HumanAgent", "ToHumanAgent")
                        .WithMany("CallHandoffs")
                        .HasForeignKey("ToHumanAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallSession");

                    b.Navigation("CallTransfer");

                    b.Navigation("FromParticipant");

                    b.Navigation("ToHumanAgent");
                });

            modelBuilder.Entity("backend.Models.Domain.CallLeg", b =>
                {
                    b.HasOne("backend.Models.Domain.CallSession", "CallSession")
                        .WithMany("Legs")
                        .HasForeignKey("CallSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallSession");
                });

            modelBuilder.Entity("backend.Models.Domain.CallParticipant", b =>
                {
                    b.HasOne("backend.Models.Domain.CallSession", "CallSession")
                        .WithMany("Participants")
                        .HasForeignKey("CallSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Domain.HumanAgent", "HumanAgent")
                        .WithMany("CallParticipants")
                        .HasForeignKey("HumanAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CallSession");

                    b.Navigation("HumanAgent");
                });

            modelBuilder.Entity("backend.Models.Domain.CallRecording", b =>
                {
                    b.HasOne("backend.Models.Domain.CallSession", "CallSession")
                        .WithMany("Recordings")
                        .HasForeignKey("CallSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallSession");
                });

            modelBuilder.Entity("backend.Models.Domain.CallSession", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Domain.CallConfiguration", "CallConfiguration")
                        .WithMany("CallSessions")
                        .HasForeignKey("CallConfigurationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Domain.SipConnection", "OriginSipConnection")
                        .WithMany()
                        .HasForeignKey("OriginSipConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Domain.PersonaVersion", "PersonaVersion")
                        .WithMany()
                        .HasForeignKey("PersonaVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithMany("CallSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Domain.WorkflowVersion", "WorkflowVersion")
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApiKey");

                    b.Navigation("CallConfiguration");

                    b.Navigation("OriginSipConnection");

                    b.Navigation("PersonaVersion");

                    b.Navigation("User");

                    b.Navigation("WorkflowVersion");
                });

            modelBuilder.Entity("backend.Models.Domain.CallTransfer", b =>
                {
                    b.HasOne("backend.Models.Domain.CallSession", "CallSession")
                        .WithMany("Transfers")
                        .HasForeignKey("CallSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Domain.SipDestination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Domain.CallParticipant", "FromParticipant")
                        .WithMany()
                        .HasForeignKey("FromParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Domain.HumanAgent", "ToHumanAgent")
                        .WithMany("CallTransfers")
                        .HasForeignKey("ToHumanAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CallSession");

                    b.Navigation("Destination");

                    b.Navigation("FromParticipant");

                    b.Navigation("ToHumanAgent");
                });

            modelBuilder.Entity("backend.Models.Domain.HumanAgent", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.User", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Modules.Identity.Models.User", "OwnerUser")
                        .WithMany("HumanAgents")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("backend.Models.Domain.HumanAgentAccessKey", b =>
                {
                    b.HasOne("backend.Models.Domain.HumanAgent", "HumanAgent")
                        .WithMany("AccessKeys")
                        .HasForeignKey("HumanAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HumanAgent");
                });

            modelBuilder.Entity("backend.Models.Domain.HumanAgentSession", b =>
                {
                    b.HasOne("backend.Models.Domain.HumanAgent", "HumanAgent")
                        .WithMany("Sessions")
                        .HasForeignKey("HumanAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HumanAgent");
                });

            modelBuilder.Entity("backend.Models.Domain.KnowledgeBase", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithMany("KnowledgeBases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Domain.KnowledgeChunk", b =>
                {
                    b.HasOne("backend.Models.Domain.KnowledgeDocument", "KnowledgeDocument")
                        .WithMany("Chunks")
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeDocument");
                });

            modelBuilder.Entity("backend.Models.Domain.KnowledgeDocument", b =>
                {
                    b.HasOne("backend.Models.Domain.KnowledgeBase", "KnowledgeBase")
                        .WithMany("Documents")
                        .HasForeignKey("KnowledgeBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeBase");
                });

            modelBuilder.Entity("backend.Models.Domain.Persona", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithMany("Personas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Domain.PersonaAction", b =>
                {
                    b.HasOne("backend.Models.Domain.ActionDefinition", "ActionDefinition")
                        .WithMany("PersonaActions")
                        .HasForeignKey("ActionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Domain.Persona", "Persona")
                        .WithMany("PersonaActions")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionDefinition");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("backend.Models.Domain.PersonaKnowledgeBase", b =>
                {
                    b.HasOne("backend.Models.Domain.KnowledgeBase", "KnowledgeBase")
                        .WithMany("PersonaKnowledgeBases")
                        .HasForeignKey("KnowledgeBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Domain.Persona", "Persona")
                        .WithMany("PersonaKnowledgeBases")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeBase");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("backend.Models.Domain.PersonaVersion", b =>
                {
                    b.HasOne("backend.Models.Domain.Persona", "Persona")
                        .WithMany("Versions")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("backend.Models.Domain.SipConnection", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Domain.SipDestination", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Domain.Subscription", b =>
                {
                    b.HasOne("backend.Models.Domain.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Domain.UsageRecord", b =>
                {
                    b.HasOne("backend.Models.Domain.CallSession", "CallSession")
                        .WithMany("UsageRecords")
                        .HasForeignKey("CallSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Modules.Identity.Models.License", "License")
                        .WithMany("UsageRecords")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Modules.Identity.Models.Partner", "Partner")
                        .WithMany("UsageRecords")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithMany("UsageRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallSession");

                    b.Navigation("License");

                    b.Navigation("Partner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Domain.Workflow", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithMany("Workflows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Domain.WorkflowExecution", b =>
                {
                    b.HasOne("backend.Models.Domain.CallSession", "CallSession")
                        .WithMany("WorkflowExecutions")
                        .HasForeignKey("CallSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Models.Domain.WorkflowVersion", "WorkflowVersion")
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallSession");

                    b.Navigation("WorkflowVersion");
                });

            modelBuilder.Entity("backend.Models.Domain.WorkflowVersion", b =>
                {
                    b.HasOne("backend.Models.Domain.Workflow", "Workflow")
                        .WithMany("Versions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.ApiKey", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.License", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.Partner", "Partner")
                        .WithMany("Licenses")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Modules.Identity.Models.PartnerPlan", "PartnerPlan")
                        .WithMany("Licenses")
                        .HasForeignKey("PartnerPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithMany("Licenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("PartnerPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.Partner", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.User", "User")
                        .WithOne("Partner")
                        .HasForeignKey("backend.Modules.Identity.Models.Partner", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.PartnerExternalCustomer", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Identity.Models.User", "PlatformUser")
                        .WithMany()
                        .HasForeignKey("PlatformUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("PlatformUser");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.PartnerPlan", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.Partner", "Partner")
                        .WithMany("PartnerPlans")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.PartnerRelationship", b =>
                {
                    b.HasOne("backend.Modules.Identity.Models.User", "CustomerUser")
                        .WithMany()
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Identity.Models.Partner", "Partner")
                        .WithMany("CustomerRelationships")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Modules.Identity.Models.User", null)
                        .WithMany("PartnerRelationships")
                        .HasForeignKey("UserId");

                    b.Navigation("CustomerUser");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.User", b =>
                {
                    b.HasOne("backend.Models.Domain.Persona", "DefaultPersona")
                        .WithMany()
                        .HasForeignKey("DefaultPersonaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultPersona");
                });

            modelBuilder.Entity("backend.Models.Domain.ActionDefinition", b =>
                {
                    b.Navigation("ActionExecutions");

                    b.Navigation("CallConfigurationActions");

                    b.Navigation("PersonaActions");
                });

            modelBuilder.Entity("backend.Models.Domain.CallConfiguration", b =>
                {
                    b.Navigation("CallConfigurationActions");

                    b.Navigation("CallSessions");
                });

            modelBuilder.Entity("backend.Models.Domain.CallSession", b =>
                {
                    b.Navigation("ActionExecutions");

                    b.Navigation("Handoffs");

                    b.Navigation("Legs");

                    b.Navigation("Participants");

                    b.Navigation("Recordings");

                    b.Navigation("Transfers");

                    b.Navigation("UsageRecords");

                    b.Navigation("WorkflowExecutions");
                });

            modelBuilder.Entity("backend.Models.Domain.CallTransfer", b =>
                {
                    b.Navigation("Handoff");
                });

            modelBuilder.Entity("backend.Models.Domain.HumanAgent", b =>
                {
                    b.Navigation("AccessKeys");

                    b.Navigation("CallHandoffs");

                    b.Navigation("CallParticipants");

                    b.Navigation("CallTransfers");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("backend.Models.Domain.KnowledgeBase", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("PersonaKnowledgeBases");
                });

            modelBuilder.Entity("backend.Models.Domain.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("backend.Models.Domain.Persona", b =>
                {
                    b.Navigation("PersonaActions");

                    b.Navigation("PersonaKnowledgeBases");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("backend.Models.Domain.Plan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("backend.Models.Domain.Workflow", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.License", b =>
                {
                    b.Navigation("UsageRecords");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.Partner", b =>
                {
                    b.Navigation("CustomerRelationships");

                    b.Navigation("Licenses");

                    b.Navigation("PartnerPlans");

                    b.Navigation("UsageRecords");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.PartnerPlan", b =>
                {
                    b.Navigation("Licenses");
                });

            modelBuilder.Entity("backend.Modules.Identity.Models.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("CallConfigurations");

                    b.Navigation("CallSessions");

                    b.Navigation("HumanAgents");

                    b.Navigation("KnowledgeBases");

                    b.Navigation("Licenses");

                    b.Navigation("Partner");

                    b.Navigation("PartnerRelationships");

                    b.Navigation("Personas");

                    b.Navigation("Subscriptions");

                    b.Navigation("UsageRecords");

                    b.Navigation("Workflows");
                });
#pragma warning restore 612, 618
        }
    }
}
