export interface CallTranscriptTurn {
  role: "ai" | "caller" | "human";
  text: string;
  timestamp: string;
  confidence: number;
}

export interface Call {
  id: string;
  callerName: string;
  callerNumber: string;
  status: "active-ai" | "active-human" | "queued" | "completed-ai" | "completed-escalated" | "missed" | "abandoned";
  duration: number | null;
  agentId: string | null;
  agentName: string | null;
  agentType: "ai" | "human" | null;
  intent: string;
  confidence: number;
  sentiment: "positive" | "neutral" | "negative";
  transcript: CallTranscriptTurn[];
  startTime: string;
  endTime: string | null;
  waitTime: number;
  resolution: "ai-resolved" | "escalated" | "unresolved" | null;
  csat: number | null;
  channel: string;
  queue: string;
  skillGroup: string;
  escalationDelay: number | null;
  apiActions: { action: string; timestamp: string }[];
  recordingUrl: string | null;
}

export interface Agent {
  id: string;
  name: string;
  type: "ai" | "human";
  status: "online" | "busy" | "break" | "offline";
  role: string;
  languages: string[];
  initials: string;
  avatarUrl: string | null;
  activeCalls: number;
  callsToday: number;
  avgHandleTime: number;
  capacity: number;
  model?: string;
}

export interface Metrics {
  activeCalls: number;
  aiHandling: number;
  humanActive: number;
  queued: number;
  avgWait: number;
  escalationRate: number;
  callsToday: number;
  autoResolveRate: number;
  csatScore: number;
  avgInferenceMs: number;
  callsPerHour: number[];
  callsPerHourYesterday: number[];
  callsPerDay: number[];
  heatmapData: number[][];
}

export const LIVEMETRICS: Metrics = {
  activeCalls: 147,
  aiHandling: 128,
  humanActive: 12,
  queued: 7,
  avgWait: 0.8,
  escalationRate: 8.2,
  callsToday: 2847,
  autoResolveRate: 94,
  csatScore: 4.7,
  avgInferenceMs: 182,
  callsPerHour: [120, 85, 54, 32, 18, 22, 68, 156, 234, 312, 298, 340, 356, 378, 412, 398, 445, 476, 502, 468, 410, 356, 288, 192],
  callsPerHourYesterday: [110, 78, 48, 28, 15, 18, 58, 142, 222, 298, 278, 322, 336, 358, 398, 382, 426, 458, 484, 448, 392, 340, 272, 178],
  callsPerDay: [2340, 2512, 2189, 2678, 2456, 2891, 2847],
  heatmapData: [
    [0.2, 0.1, 0.05, 0.02, 0.01, 0.03, 0.15, 0.35, 0.52, 0.68, 0.62, 0.74, 0.78, 0.82, 0.89, 0.85, 0.94, 1.0, 1.0, 0.96, 0.88, 0.72, 0.56, 0.38],
    [0.18, 0.08, 0.04, 0.02, 0.01, 0.02, 0.12, 0.32, 0.48, 0.64, 0.58, 0.7, 0.74, 0.78, 0.85, 0.82, 0.9, 0.96, 0.98, 0.92, 0.84, 0.68, 0.52, 0.34],
    [0.22, 0.12, 0.06, 0.03, 0.02, 0.04, 0.18, 0.38, 0.56, 0.72, 0.65, 0.78, 0.82, 0.86, 0.92, 0.88, 0.96, 1.0, 1.0, 0.98, 0.92, 0.76, 0.6, 0.42],
    [0.25, 0.15, 0.08, 0.05, 0.03, 0.05, 0.22, 0.42, 0.6, 0.76, 0.7, 0.82, 0.86, 0.9, 0.95, 0.92, 0.98, 1.0, 1.0, 1.0, 0.94, 0.8, 0.64, 0.46],
    [0.28, 0.18, 0.1, 0.06, 0.04, 0.08, 0.25, 0.45, 0.64, 0.8, 0.74, 0.86, 0.9, 0.94, 1.0, 0.96, 1.0, 1.0, 1.0, 1.0, 0.98, 0.84, 0.68, 0.5],
    [0.12, 0.06, 0.03, 0.02, 0.01, 0.02, 0.08, 0.2, 0.32, 0.44, 0.4, 0.5, 0.54, 0.58, 0.62, 0.6, 0.68, 0.74, 0.72, 0.7, 0.6, 0.48, 0.36, 0.22],
    [0.05, 0.03, 0.02, 0.01, 0.01, 0.02, 0.06, 0.15, 0.24, 0.35, 0.3, 0.38, 0.4, 0.44, 0.48, 0.46, 0.52, 0.58, 0.56, 0.52, 0.44, 0.34, 0.24, 0.14],
  ],
};

export const CALLS: Call[] = [
  {
    id: "call-001",
    callerName: "Alice Morgan",
    callerNumber: "+1 (415) 555-0123",
    status: "active-ai",
    duration: 262,
    agentId: "agent-ai-01",
    agentName: "Noor",
    agentType: "ai",
    intent: "refund",
    confidence: 0.96,
    sentiment: "neutral",
    startTime: new Date(Date.now() - 300000).toISOString(),
    endTime: null,
    waitTime: 0.3,
    resolution: null,
    csat: null,
    channel: "PSTN",
    queue: "billing-support",
    skillGroup: "billing_refunds",
    escalationDelay: null,
    apiActions: [],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "Thank you for calling Tandem. I'm Noor — how can I help you today?", timestamp: "00:00", confidence: 1 },
      { role: "caller", text: "Hi, I was charged twice for my last order. Can you fix that?", timestamp: "00:04", confidence: 0.98 },
      { role: "ai", text: "I can absolutely help with that. I see the duplicate charge from order #TND-8841 on Tuesday — $47.50. I'll refund it to your card now.", timestamp: "00:08", confidence: 0.97 },
      { role: "caller", text: "Great, how long does that take?", timestamp: "00:15", confidence: 0.99 },
      { role: "ai", text: "Usually 2-3 business days. You'll get a confirmation email in about 30 seconds. Is there anything else I can help with?", timestamp: "00:18", confidence: 0.95 },
    ],
  },
  {
    id: "call-002",
    callerName: "James Chen",
    callerNumber: "+1 (310) 555-0456",
    status: "active-human",
    duration: 75,
    agentId: "agent-human-01",
    agentName: "Marco",
    agentType: "human",
    intent: "complaint",
    confidence: 0.42,
    sentiment: "negative",
    startTime: new Date(Date.now() - 120000).toISOString(),
    endTime: null,
    waitTime: 0.5,
    resolution: null,
    csat: null,
    channel: "PSTN",
    queue: "escalation",
    skillGroup: "vip_retention",
    escalationDelay: 0.4,
    apiActions: [{ action: "refund_processed", timestamp: "00:06" }, { action: "crm_note_created", timestamp: "00:08" }],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "I understand you're frustrated about the software license renewal. Let me get someone who can handle this personally.", timestamp: "00:00", confidence: 0.88 },
      { role: "caller", text: "I've been on hold for 20 minutes. This is ridiculous.", timestamp: "00:04", confidence: 0.97 },
      { role: "human", text: "Hi James, this is Marco — I've got your full history pulled up. I understand there's been an issue with the renewal. Let's get it sorted.", timestamp: "00:12", confidence: 1 },
    ],
  },
  {
    id: "call-003",
    callerName: "Sarah Ruiz",
    callerNumber: "+1 (212) 555-0789",
    status: "queued",
    duration: null,
    agentId: null,
    agentName: null,
    agentType: null,
    intent: "shipping",
    confidence: 0.91,
    sentiment: "neutral",
    startTime: new Date(Date.now() - 30000).toISOString(),
    endTime: null,
    waitTime: 0,
    resolution: null,
    csat: null,
    channel: "WebRTC",
    queue: "logistics",
    skillGroup: "shipping_tracking",
    escalationDelay: null,
    apiActions: [],
    recordingUrl: null,
    transcript: [],
  },
  {
    id: "call-004",
    callerName: "David Park",
    callerNumber: "+1 (650) 555-0321",
    status: "active-ai",
    duration: 180,
    agentId: "agent-ai-02",
    agentName: "Atlas",
    agentType: "ai",
    intent: "tech-support",
    confidence: 0.88,
    sentiment: "neutral",
    startTime: new Date(Date.now() - 240000).toISOString(),
    endTime: null,
    waitTime: 0.2,
    resolution: null,
    csat: null,
    channel: "PSTN",
    queue: "tech-support-l1",
    skillGroup: "connectivity",
    escalationDelay: null,
    apiActions: [],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "Atlas here — I see your device is offline since 3:14 PM. Let's run a quick diagnostic.", timestamp: "00:00", confidence: 1 },
      { role: "caller", text: "My WiFi keeps dropping every 15 minutes. I've already restarted three times.", timestamp: "00:03", confidence: 0.99 },
      { role: "ai", text: "Let me check the line quality. I'm seeing intermittent packet loss on hop 4 — looks like it's on your ISP's side. I can run an extended stability test for the next hour and email you the report.", timestamp: "00:07", confidence: 0.92 },
    ],
  },
  {
    id: "call-005",
    callerName: "Maria Santos",
    callerNumber: "+1 (786) 555-0654",
    status: "active-ai",
    duration: 410,
    agentId: "agent-ai-03",
    agentName: "June",
    agentType: "ai",
    intent: "sales",
    confidence: 0.94,
    sentiment: "positive",
    startTime: new Date(Date.now() - 480000).toISOString(),
    endTime: null,
    waitTime: 0.4,
    resolution: null,
    csat: null,
    channel: "PSTN",
    queue: "sales",
    skillGroup: "renewals",
    escalationDelay: null,
    apiActions: [],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "Hi Maria! Your annual plan renews next Tuesday. I found a plan that gives you 40% more API calls for only $18/month more.", timestamp: "00:00", confidence: 1 },
      { role: "caller", text: "Oh, I was actually thinking about downgrading. Show me what you've got.", timestamp: "00:05", confidence: 0.98 },
      { role: "ai", text: "Let me compare — keeping your current plan is $199/mo. The Plus plan at $217/mo gives you 40% more quota, priority support, and 3 new AI agents. Your team of 12 would save about 11 hours a week.", timestamp: "00:09", confidence: 0.96 },
      { role: "caller", text: "That actually sounds worth it. Go ahead and switch me to Plus.", timestamp: "00:18", confidence: 0.99 },
    ],
  },
  {
    id: "call-006",
    callerName: "Robert Kim",
    callerNumber: "+1 (408) 555-0987",
    status: "completed-ai",
    duration: 195,
    agentId: "agent-ai-01",
    agentName: "Noor",
    agentType: "ai",
    intent: "billing",
    confidence: 0.98,
    sentiment: "positive",
    startTime: new Date(Date.now() - 1800000).toISOString(),
    endTime: new Date(Date.now() - 1600000).toISOString(),
    waitTime: 0.6,
    resolution: "ai-resolved",
    csat: 4.9,
    channel: "PSTN",
    queue: "billing-support",
    skillGroup: "billing_inquiries",
    escalationDelay: null,
    apiActions: [{ action: "invoice_emailed", timestamp: "00:22" }, { action: "payment_link_generated", timestamp: "00:25" }],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "Billing support — Noor speaking. How can I help?", timestamp: "00:00", confidence: 1 },
      { role: "caller", text: "I need a copy of my last three invoices for accounting.", timestamp: "00:02", confidence: 0.99 },
      { role: "ai", text: "Sent to robert.kim@example.com. January: $1,240, February: $1,310, March: $1,280. Would you like me to set up automatic invoice forwarding to your accounting team?", timestamp: "00:06", confidence: 0.98 },
      { role: "caller", text: "Yes please, send them to accounting@kimcorp.com.", timestamp: "00:14", confidence: 0.99 },
      { role: "ai", text: "Done. They'll receive PDFs on the 1st of each month. Anything else?", timestamp: "00:16", confidence: 0.99 },
      { role: "caller", text: "That's it, thanks Noor — you were great.", timestamp: "00:21", confidence: 0.99 },
    ],
  },
  {
    id: "call-007",
    callerName: "Thomas Wright",
    callerNumber: "+1 (512) 555-0345",
    status: "completed-escalated",
    duration: 540,
    agentId: "agent-human-02",
    agentName: "Lea",
    agentType: "human",
    intent: "complaint",
    confidence: 0.35,
    sentiment: "negative",
    startTime: new Date(Date.now() - 3600000).toISOString(),
    endTime: new Date(Date.now() - 3060000).toISOString(),
    waitTime: 1.2,
    resolution: "escalated",
    csat: 3.8,
    channel: "SIP",
    queue: "escalation",
    skillGroup: "vip_retention",
    escalationDelay: 0.3,
    apiActions: [{ action: "priority_case_opened", timestamp: "00:38" }, { action: "crm_ticket_TND-9921", timestamp: "01:12" }, { action: "refund_partial_$89", timestamp: "04:20" }],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "I understand this is about a service outage that affected your team. Let me connect you with someone who has full authority to resolve this.", timestamp: "00:00", confidence: 0.87 },
      { role: "caller", text: "We lost an entire day of work because of this. I want to speak to a manager.", timestamp: "00:06", confidence: 0.96 },
      { role: "human", text: "Thomas, this is Lea — I manage the escalation desk. I've reviewed your case and I completely understand. Let me propose a credit and a direct line to our engineering team for the next 30 days.", timestamp: "00:18", confidence: 1 },
      { role: "caller", text: "Alright, what are you offering?", timestamp: "00:26", confidence: 0.98 },
      { role: "human", text: "A full day's credit — $89 — plus priority support routing for 30 days, and I'm personally flagging your account so any future issues bypass tier 1.", timestamp: "00:28", confidence: 1 },
      { role: "caller", text: "Okay. That's fair. Thank you Lea.", timestamp: "00:42", confidence: 0.97 },
    ],
  },
  {
    id: "call-008",
    callerName: "Emily Foster",
    callerNumber: "+1 (303) 555-0765",
    status: "missed",
    duration: null,
    agentId: null,
    agentName: null,
    agentType: null,
    intent: "scheduling",
    confidence: 0,
    sentiment: "neutral",
    startTime: new Date(Date.now() - 5400000).toISOString(),
    endTime: null,
    waitTime: 0,
    resolution: "unresolved",
    csat: null,
    channel: "PSTN",
    queue: "logistics",
    skillGroup: "bookings",
    escalationDelay: null,
    apiActions: [],
    recordingUrl: null,
    transcript: [],
  },
  {
    id: "call-009",
    callerName: "Luis Garcia",
    callerNumber: "+1 (214) 555-0128",
    status: "abandoned",
    duration: 45,
    agentId: null,
    agentName: null,
    agentType: null,
    intent: "tech-support",
    confidence: 0,
    sentiment: "neutral",
    startTime: new Date(Date.now() - 7200000).toISOString(),
    endTime: new Date(Date.now() - 7155000).toISOString(),
    waitTime: 45,
    resolution: "unresolved",
    csat: null,
    channel: "WebRTC",
    queue: "tech-support-l1",
    skillGroup: "general_tech",
    escalationDelay: null,
    apiActions: [],
    recordingUrl: null,
    transcript: [],
  },
  {
    id: "call-010",
    callerName: "Priya Patel",
    callerNumber: "+1 (617) 555-0459",
    status: "completed-ai",
    duration: 148,
    agentId: "agent-ai-04",
    agentName: "Priya",
    agentType: "ai",
    intent: "scheduling",
    confidence: 0.97,
    sentiment: "positive",
    startTime: new Date(Date.now() - 14400000).toISOString(),
    endTime: new Date(Date.now() - 14252000).toISOString(),
    waitTime: 0.3,
    resolution: "ai-resolved",
    csat: 4.8,
    channel: "PSTN",
    queue: "logistics",
    skillGroup: "bookings",
    escalationDelay: null,
    apiActions: [{ action: "flight_rebooked_DL882", timestamp: "00:34" }, { action: "calendar_updated", timestamp: "00:38" }],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "Bookings desk — Priya here. What can I rebook for you?", timestamp: "00:00", confidence: 1 },
      { role: "caller", text: "My flight tomorrow got cancelled. I need to be in Chicago by noon.", timestamp: "00:02", confidence: 0.99 },
      { role: "ai", text: "Delta 882 at 6:15 AM — lands at 9:40 AM. One seat left in economy plus. Shall I book it?", timestamp: "00:06", confidence: 0.98 },
      { role: "caller", text: "Perfect, book it.", timestamp: "00:10", confidence: 0.99 },
      { role: "ai", text: "Confirmed — DL882, seat 14C, arrival 9:40 AM. Check-in opens at 4:15 AM. I've added it to your calendar and sent the boarding info.", timestamp: "00:12", confidence: 0.99 },
    ],
  },
  {
    id: "call-011",
    callerName: "Nina Okonkwo",
    callerNumber: "+1 (404) 555-0782",
    status: "active-ai",
    duration: 92,
    agentId: "agent-ai-02",
    agentName: "Atlas",
    agentType: "ai",
    intent: "tech-support",
    confidence: 0.85,
    sentiment: "neutral",
    startTime: new Date(Date.now() - 150000).toISOString(),
    endTime: null,
    waitTime: 0.1,
    resolution: null,
    csat: null,
    channel: "WebRTC",
    queue: "tech-support-l1",
    skillGroup: "software_config",
    escalationDelay: null,
    apiActions: [],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "Atlas, technical support. What's not working?", timestamp: "00:00", confidence: 1 },
      { role: "caller", text: "The new dashboard update made all my reports blank. I have a client meeting in 20 minutes.", timestamp: "00:02", confidence: 0.99 },
      { role: "ai", text: "Let me roll you back to the previous version. It'll take about 90 seconds and your data is safe. I'm starting now.", timestamp: "00:07", confidence: 0.91 },
    ],
  },
  {
    id: "call-012",
    callerName: "Kenji Yamamoto",
    callerNumber: "+1 (808) 555-0234",
    status: "completed-ai",
    duration: 210,
    agentId: "agent-ai-03",
    agentName: "June",
    agentType: "ai",
    intent: "sales",
    confidence: 0.93,
    sentiment: "positive",
    startTime: new Date(Date.now() - 21600000).toISOString(),
    endTime: new Date(Date.now() - 21390000).toISOString(),
    waitTime: 0.5,
    resolution: "ai-resolved",
    csat: 4.6,
    channel: "PSTN",
    queue: "sales",
    skillGroup: "new_business",
    escalationDelay: null,
    apiActions: [{ action: "account_created", timestamp: "01:10" }, { action: "trial_activated", timestamp: "01:15" }],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "June from Tandem sales. I hear you're looking at our enterprise plan?", timestamp: "00:00", confidence: 1 },
      { role: "caller", text: "Yes, we handle about 2,000 calls a day and need something that scales.", timestamp: "00:03", confidence: 0.99 },
      { role: "ai", text: "2,000 calls — our Enterprise tier handles that with 4 dedicated AI agents and your team of 8 for escalations. At your volume you'd save roughly $14,200/month versus full human staffing. Want me to set up a 5-day pilot?", timestamp: "00:07", confidence: 0.94 },
      { role: "caller", text: "Yes, let's do the pilot. Can we start Monday?", timestamp: "00:15", confidence: 0.98 },
      { role: "ai", text: "Monday works. I've created your account and activated the trial. You'll get an onboarding email in 5 minutes with everything you need.", timestamp: "00:17", confidence: 0.99 },
    ],
  },
  {
    id: "call-013",
    callerName: "Fatima Hassan",
    callerNumber: "+1 (313) 555-0678",
    status: "completed-escalated",
    duration: 432,
    agentId: "agent-human-01",
    agentName: "Marco",
    agentType: "human",
    intent: "complaint",
    confidence: 0.28,
    sentiment: "negative",
    startTime: new Date(Date.now() - 43200000).toISOString(),
    endTime: new Date(Date.now() - 42768000).toISOString(),
    waitTime: 2.1,
    resolution: "escalated",
    csat: 4.2,
    channel: "SIP",
    queue: "escalation",
    skillGroup: "executive_care",
    escalationDelay: 0.5,
    apiActions: [{ action: "exec_case_created", timestamp: "01:20" }, { action: "full_refund_$340", timestamp: "03:45" }, { action: "account_credited", timestamp: "04:10" }],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "I understand this has been frustrating. Let me transfer you to our executive care team.", timestamp: "00:00", confidence: 0.72 },
      { role: "caller", text: "I've been transferred four times already. I want this resolved NOW.", timestamp: "00:05", confidence: 0.95 },
      { role: "human", text: "Ms. Hassan, I'm Marco from executive care. I see the full history — the duplicate subscription, the failed cancellations. I'm issuing a full refund of $340 right now and personally ensuring this doesn't happen again.", timestamp: "00:26", confidence: 1 },
      { role: "caller", text: "Thank you. Finally someone who actually does something.", timestamp: "00:38", confidence: 0.96 },
      { role: "human", text: "You'll see the refund in 24 hours. I'm also giving you 3 months free — check your email for the confirmation in about one minute.", timestamp: "00:42", confidence: 1 },
    ],
  },
  {
    id: "call-014",
    callerName: "Omar Sylla",
    callerNumber: "+1 (347) 555-0198",
    status: "active-ai",
    duration: 35,
    agentId: "agent-ai-04",
    agentName: "Priya",
    agentType: "ai",
    intent: "scheduling",
    confidence: 0.95,
    sentiment: "neutral",
    startTime: new Date(Date.now() - 60000).toISOString(),
    endTime: null,
    waitTime: 0.2,
    resolution: null,
    csat: null,
    channel: "PSTN",
    queue: "logistics",
    skillGroup: "bookings",
    escalationDelay: null,
    apiActions: [],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "Priya at bookings. What can I help you schedule?", timestamp: "00:00", confidence: 1 },
      { role: "caller", text: "I need to move my hotel check-in from Wednesday to Thursday.", timestamp: "00:02", confidence: 0.99 },
      { role: "ai", text: "Let me pull up your reservation — one moment.", timestamp: "00:06", confidence: 0.98 },
    ],
  },
  {
    id: "call-015",
    callerName: "Sophie Laurent",
    callerNumber: "+1 (504) 555-0443",
    status: "completed-ai",
    duration: 92,
    agentId: "agent-ai-01",
    agentName: "Noor",
    agentType: "ai",
    intent: "billing",
    confidence: 0.99,
    sentiment: "positive",
    startTime: new Date(Date.now() - 28800000).toISOString(),
    endTime: new Date(Date.now() - 28708000).toISOString(),
    waitTime: 0.4,
    resolution: "ai-resolved",
    csat: 5.0,
    channel: "WebRTC",
    queue: "billing-support",
    skillGroup: "billing_inquiries",
    escalationDelay: null,
    apiActions: [{ action: "subscription_downgraded", timestamp: "00:42" }, { action: "confirmation_emailed", timestamp: "00:48" }],
    recordingUrl: null,
    transcript: [
      { role: "ai", text: "Billing — Noor. How can I help?", timestamp: "00:00", confidence: 1 },
      { role: "caller", text: "I want to downgrade from Pro to Starter. We're not using all the features.", timestamp: "00:02", confidence: 0.99 },
      { role: "ai", text: "Understood. Your Pro plan is $199/mo. Starter is $79/mo — same core features, just lower limits. The change takes effect next billing cycle on the 15th. Confirm?", timestamp: "00:04", confidence: 0.99 },
      { role: "caller", text: "Yes, confirmed.", timestamp: "00:12", confidence: 0.99 },
      { role: "ai", text: "Done. You'll save $1,440/year. Confirmation sent to your email. Anything else?", timestamp: "00:14", confidence: 0.99 },
      { role: "caller", text: "Nope, that was easy. Thanks!", timestamp: "00:18", confidence: 0.99 },
    ],
  },
];

export const AGENTS: Agent[] = [
  {
    id: "agent-ai-01",
    name: "Noor",
    type: "ai",
    status: "busy",
    role: "Billing & refunds",
    languages: ["en", "ar", "fr", "tr"],
    initials: "NO",
    avatarUrl: null,
    activeCalls: 31,
    callsToday: 412,
    avgHandleTime: 168,
    capacity: 85,
    model: "tandem-mistral-7b-v3",
  },
  {
    id: "agent-ai-02",
    name: "Atlas",
    type: "ai",
    status: "busy",
    role: "Technical support",
    languages: ["en", "es", "de", "pt"],
    initials: "AT",
    avatarUrl: null,
    activeCalls: 28,
    callsToday: 378,
    avgHandleTime: 224,
    capacity: 78,
    model: "tandem-llama3-70b-ts",
  },
  {
    id: "agent-ai-03",
    name: "June",
    type: "ai",
    status: "busy",
    role: "Sales & renewals",
    languages: ["en", "fr", "ja"],
    initials: "JU",
    avatarUrl: null,
    activeCalls: 24,
    callsToday: 356,
    avgHandleTime: 198,
    capacity: 72,
    model: "tandem-mistral-7b-v3",
  },
  {
    id: "agent-ai-04",
    name: "Priya",
    type: "ai",
    status: "busy",
    role: "Bookings & logistics",
    languages: ["en", "hi", "it"],
    initials: "PR",
    avatarUrl: null,
    activeCalls: 27,
    callsToday: 401,
    avgHandleTime: 145,
    capacity: 80,
    model: "tandem-llama3-70b-ts",
  },
  {
    id: "agent-human-01",
    name: "Marco",
    type: "human",
    status: "busy",
    role: "Escalation lead",
    languages: ["en", "es"],
    initials: "MC",
    avatarUrl: "https://images.pexels.com/photos/1546912/pexels-photo-1546912.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=240&w=240",
    activeCalls: 2,
    callsToday: 28,
    avgHandleTime: 340,
    capacity: 55,
  },
  {
    id: "agent-human-02",
    name: "Lea",
    type: "human",
    status: "busy",
    role: "Senior specialist",
    languages: ["en", "nl", "de"],
    initials: "LE",
    avatarUrl: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=240&w=240",
    activeCalls: 1,
    callsToday: 22,
    avgHandleTime: 380,
    capacity: 45,
  },
  {
    id: "agent-human-03",
    name: "Sam",
    type: "human",
    status: "online",
    role: "Technical support L2",
    languages: ["en", "pt"],
    initials: "SA",
    avatarUrl: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=240&w=240",
    activeCalls: 0,
    callsToday: 19,
    avgHandleTime: 298,
    capacity: 24,
  },
  {
    id: "agent-human-04",
    name: "Tanya",
    type: "human",
    status: "break",
    role: "Customer success",
    languages: ["en", "fr", "ar"],
    initials: "TA",
    avatarUrl: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=240&w=240",
    activeCalls: 0,
    callsToday: 15,
    avgHandleTime: 312,
    capacity: 0,
  },
  {
    id: "agent-human-05",
    name: "Diego",
    type: "human",
    status: "offline",
    role: "Night shift lead",
    languages: ["en", "es", "it"],
    initials: "DI",
    avatarUrl: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=240&w=240",
    activeCalls: 0,
    callsToday: 0,
    avgHandleTime: 290,
    capacity: 0,
  },
];

export const TOP_INTENTS = [
  { intent: "Refund & returns", count: 712, pct: 34 },
  { intent: "Shipping & tracking", count: 460, pct: 22 },
  { intent: "Billing inquiries", count: 376, pct: 18 },
  { intent: "Technical support", count: 293, pct: 14 },
  { intent: "Complaints", count: 126, pct: 6 },
  { intent: "Sales & upgrades", count: 84, pct: 4 },
  { intent: "Other", count: 42, pct: 2 },
];

export const QUEUES = [
  { name: "Billing Support", active: 2, wait: 0.3, agents: 2 },
  { name: "Technical Support L1", active: 3, wait: 0.5, agents: 2 },
  { name: "Sales", active: 2, wait: 0.4, agents: 2 },
  { name: "Logistics", active: 1, wait: 0.2, agents: 2 },
  { name: "Escalation", active: 2, wait: 0.8, agents: 2 },
];