[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=10.18.0.0/16
local_net=172.17.0.0/16
local_net=127.0.0.1/8
external_media_address=167.71.66.188
external_signaling_address=167.71.66.188

[101]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw,gsm
auth=101
aors=101
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
direct_media=no

[101]
type=auth
auth_type=userpass
password=password101
username=101

[101]
type=aor
max_contacts=1

[102]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw,gsm
auth=102
aors=102
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
direct_media=no

[102]
type=auth
auth_type=userpass
password=password102
username=102

[102]
type=aor
max_contacts=1

[livekit]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw,gsm
aors=livekit
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
direct_media=no

[livekit]
type=aor
contact=sip:127.0.0.1:5061
